Add logging function to PXF CLI
* PXF CLI writes log messages to $PXF_LOGDIR/admin/pxf-cli-YYYY-MM.log
* Log lines are prefixed with a timestamp and the PID of the shell
  script to help identify all log messages from a single invocation of
  the PXF CLI

diff --git a/server/pxf-service/src/scripts/pxf b/server/pxf-service/src/scripts/pxf
--- a/server/pxf-service/src/scripts/pxf
+++ b/server/pxf-service/src/scripts/pxf
@@ -53,6 +53,10 @@ export JAVA_HOME=${JAVA_HOME:=/usr/java/default}
 # Path to Log directory
 export PXF_LOGDIR=${PXF_LOGDIR:=${PXF_BASE}/logs}
 
+export PXF_CLI_LOGDIR="${PXF_LOGDIR}/admin"
+PXF_CLI_LOGFILE="${PXF_CLI_LOGDIR}/pxf-cli-$(date +%Y-%m).log"
+export PXF_CLI_LOGFILE
+
 # Path to Run directory
 export PXF_RUNDIR=${PXF_RUNDIR:=${PXF_BASE}/run}
 
@@ -118,13 +122,19 @@ function failWithHint() {
     exit 1
 }
 
+function log() {
+    printf "%s\t[%d]\t%s\n" "$(date '+%Y-%m-%d %H:%M:%S.%3N %Z')" "${BASHPID}" "$*" >>"${PXF_CLI_LOGFILE}"
+}
+
 # determines whether the application is running
 function isRunning() {
+    log "Checking if PXF process with PID=$1 exists"
     ps -o pid,command -p "$1" | grep 'pxf-app' &> /dev/null
 }
 
 # creates the runtime directory structure inside $PXF_BASE
 function createPxfBaseDirectories() {
+    log "Creating PXF runtime directory structure in ${PXF_BASE}"
     install -m 744 -d "${PXF_BASE}/conf"
     install -m 744 -d "${PXF_BASE}/lib"
     install -m 744 -d "${PXF_BASE}/lib/native"
@@ -137,6 +147,7 @@ function createPxfBaseDirectories() {
 
 # copies configuration files inside $PXF_BASE
 function copyConfigurationFilesToPxfBase() {
+    log "Copying PXF configuration files from ${PXF_HOME} to ${PXF_BASE}"
     cp -Lv "${PXF_HOME}/conf/pxf-application.properties" "${PXF_BASE}/conf"
     cp -Lv "${PXF_HOME}/conf/pxf-env.sh"                 "${PXF_BASE}/conf"
     cp -Lv "${PXF_HOME}/conf/pxf-log4j2.xml"             "${PXF_BASE}/conf"
@@ -322,6 +333,7 @@ function doStart() {
 }
 
 function do_start() {
+    log "Starting PXF service..."
     if [[ -f "$pid_file" ]]; then
         pid=$(cat "$pid_file")
         isRunning "$pid" && { echoYellow "PXF is already running [pid=$pid]"; return 0; }
@@ -354,6 +366,8 @@ function do_start() {
     disown $pid
     echo "$pid" > "$pid_file"
 
+    log "Started PXF service on port ${PXF_PORT} - PID=${pid}"
+
     [[ -z $pid ]] && fail "Failed to start PXF"
     echoGreen "PXF started [pid=$pid]. Listening on port $PXF_PORT";
 }
@@ -369,11 +383,21 @@ function doStop() {
     checkJavaHome
     warnUserEnvScript
 
+    log "Stopping PXF service..."
     working_dir=$(dirname "$jarfile")
     pushd "$working_dir" > /dev/null
-    [[ -f $pid_file ]] || { echoYellow "Not running (pidfile not found). Is PXF running? Stop aborted."; return 0; }
+    if [[ ! -f $pid_file ]]; then
+        log "No pidfile=${pid_file} for PXF found"
+        echoYellow "Not running (pidfile not found). Is PXF running? Stop aborted."
+        return 0
+    fi
     pid=$(cat "$pid_file")
-    isRunning "$pid" || { echoYellow "Not running (process ${pid}). Removing stale pid file '$pid_file'."; rm -f "$pid_file"; return 0; }
+    if ! isRunning "$pid"; then
+        log "No running PXF process with PID=${pid} found; removing stale pidfile"
+        echoYellow "Not running (process ${pid}). Removing stale pid file '$pid_file'."
+        rm -f "$pid_file"
+        return 0
+    fi
 
     echoYellow "Stopping PXF [pid=$pid]..."
     do_stop "$pid" "$pid_file" || do_stop "$pid" "$pid_file" "-f"
@@ -384,12 +408,18 @@ function do_stop() {
     local killcmd=(kill)
     [[ $3 == -f ]] && killcmd+=(-9)
     killcmd+=("$1")
+    log "Attempting to stop PXF with '${killcmd[*]}'"
     "${killcmd[@]}" &> /dev/null || { echoRed "Unable to terminate process $1"; return 1; }
     for i in $(seq 1 $STOP_WAIT_TIME); do
         isRunning "$1" || { echoGreen "PXF stopped [$1]"; rm -f "$2"; return 0; }
-        [[ $i -eq STOP_WAIT_TIME/2 ]] && "${killcmd[@]}" &> /dev/null
+        log "PXF process with PID=$1 is still running..."
+        if [[ $i -eq STOP_WAIT_TIME/2 ]]; then
+            log "Attempting to stop PXF again with '${killcmd[*]}'"
+            "${killcmd[@]}" &> /dev/null
+        fi
         sleep 1
     done
+    log "Unable to stop process PID=$1 with '${killcmd[*]}'"
     echoRed "Unable to terminate process $1"
     return 1
 }
@@ -402,7 +432,11 @@ function doStatus() {
 
     working_dir="$(dirname "${jarfile}")"
     pushd "${working_dir}" >/dev/null
-    [[ -s "${pid_file}" ]] || { echoRed 'ERROR: PXF is down - the application is not running'; return 3; }
+    if [[ ! -s "${pid_file}" ]]; then
+        log "PXF pidfile '${pid_file}' does not exist"
+        echoRed 'ERROR: PXF is down - the application is not running'
+        return 3
+    fi
     pid="$(cat "${pid_file}")"
     isRunning "${pid}" || { echoRed "ERROR: PXF is down - process ${pid} not found"; return 1; }
     echoGreen "PXF is listening on port $PXF_PORT"
@@ -416,6 +450,7 @@ function doSync() {
         fail 'A destination hostname must be provided'
     fi
     warnUserEnvScript
+    log "Synchronizing PXF configuration to ${target_host}"
     rsync -az${DELETE:+ --delete} -e "ssh -o StrictHostKeyChecking=no" "$PXF_BASE"/{conf,lib,servers} "${target_host}:$PXF_BASE"
 }
 
@@ -425,6 +460,7 @@ function doCluster() {
     if [[ ${cmd} != init ]] && [[ ${cmd} != prepare ]]; then
         warnUserEnvScript
     fi
+    log "Running command '${cmd}' on PXF cluster"
     "${parent_script_dir}/bin/pxf-cli" "$@"
 }
 
@@ -436,6 +472,8 @@ function warnUserEnvScript() {
 pxf_script_command=$1
 
 silent=false
+
+[[ -d "${PXF_CLI_LOGDIR}" ]] || mkdir "${PXF_CLI_LOGDIR}"
 
 validate_user
 
