Fix pxf register command (#1047)
The pxf register command assumes that $GPHOME/share/postgresql/extension
is writable by the user running the command (usually gpadmin). The GPDB
installation docs include a step for changing the ownership of the GPDB
installation directory but if this step is skipped, then pxf register
will fail. As it is currently implemented, the step of copying the
control file into $GPHOME fails but does not cause the pxf utility to
exit with a non-zero value. This in turn causes the pxf cluster register
command to not recognize the pxf register command failure and not print
the stderr output of the command. This makes it seem like the register
command has succeeded until the user attempts to call CREATE EXTENSION
pxf in psql.

This commit replaces the usage of cp and chmod with install and
explicitly adds a failure case if the install fails.

Authored-by: Bradford D. Boyle <bradfordb@vmware.com>

diff --git a/server/pxf-service/src/scripts/pxf b/server/pxf-service/src/scripts/pxf
--- a/server/pxf-service/src/scripts/pxf
+++ b/server/pxf-service/src/scripts/pxf
@@ -260,8 +260,7 @@ function installExtensions() {
             echoGreen "Installing Greenplum External Table PXF Extension into '${GPHOME}'"
 
             local target_control_file="${GPHOME}/share/postgresql/extension/pxf.control"
-            cp -Lv "${parent_script_dir}/gpextable/pxf.control" "${target_control_file}"
-            chmod 644 "${target_control_file}"
+            install --verbose --mode=0644 "${parent_script_dir}/gpextable/pxf.control" "${target_control_file}" || fail "cannot install pxf.control to '${target_control_file}'"
         fi
     fi
     if [[ -d ${parent_script_dir}/fdw ]]; then
@@ -273,8 +272,7 @@ function installExtensions() {
             echoGreen "Installing Greenplum Foreign Data Wrapper PXF Extension into '${GPHOME}'"
 
             local target_control_file="${GPHOME}/share/postgresql/extension/pxf_fdw.control"
-            cp -Lv "${parent_script_dir}/fdw/pxf_fdw.control" "${target_control_file}"
-            chmod 644 "${target_control_file}"
+            install --verbose --mode=0644 "${parent_script_dir}/fdw/pxf_fdw.control" "${target_control_file}" || fail "cannot install pxf_fdw.control to '${target_control_file}'"
         fi
     fi
 }
